import type { Category, CityEvent, Interest, Place } from "./types"

export const CITIES = ["Dubai, UAE"] as const

export const CATEGORIES: Category[] = [
  "Food",
  "Attractions",
  "Events",
  "Culture",
  "Hidden Gems",
  "Shopping",
  "Outdoors",
]

export const INTERESTS: Interest[] = ["Food", "Culture", "Music", "Art", "Outdoors", "Shopping", "History"]

export const PLACES: Place[] = [
  {
    id: "burj-khalifa",
    name: "Burj Khalifa",
    category: "Attractions",
    coords: { x: 52, y: 48 },
    cost: 169,
    duration: 90,
    rating: 4.8,
    priceLevel: 4,
    distanceKm: 1.2,
    open: true,
    hiddenGem: false,
    description: "The world's tallest building with an observation deck above the clouds.",
    tags: ["Culture", "History"],
  },
  {
    id: "dubai-mall",
    name: "The Dubai Mall",
    category: "Shopping",
    coords: { x: 56, y: 52 },
    cost: 0,
    duration: 120,
    rating: 4.7,
    priceLevel: 3,
    distanceKm: 1.4,
    open: true,
    hiddenGem: false,
    description: "One of the largest malls on earth, complete with an aquarium and fountains.",
    tags: ["Shopping", "Food"],
  },
  {
    id: "al-seef",
    name: "Al Seef",
    category: "Culture",
    coords: { x: 44, y: 34 },
    cost: 0,
    duration: 75,
    rating: 4.6,
    priceLevel: 2,
    distanceKm: 4.1,
    open: true,
    hiddenGem: false,
    description: "A waterfront district blending old-Dubai architecture with modern cafes.",
    tags: ["Culture", "History", "Food"],
  },
  {
    id: "al-fahidi",
    name: "Al Fahidi Historical District",
    category: "Culture",
    coords: { x: 40, y: 30 },
    cost: 0,
    duration: 90,
    rating: 4.7,
    priceLevel: 1,
    distanceKm: 4.6,
    open: true,
    hiddenGem: false,
    description: "Wind-tower alleyways preserving Dubai's pre-oil heritage.",
    tags: ["Culture", "History", "Art"],
  },
  {
    id: "dubai-creek",
    name: "Dubai Creek",
    category: "Outdoors",
    coords: { x: 46, y: 28 },
    cost: 1,
    duration: 45,
    rating: 4.5,
    priceLevel: 1,
    distanceKm: 5.0,
    open: true,
    hiddenGem: false,
    description: "Cross the historic waterway on a traditional abra water taxi.",
    tags: ["History", "Outdoors"],
  },
  {
    id: "gold-souk",
    name: "Gold Souk",
    category: "Shopping",
    coords: { x: 43, y: 22 },
    cost: 0,
    duration: 60,
    rating: 4.4,
    priceLevel: 2,
    distanceKm: 6.2,
    open: true,
    hiddenGem: false,
    description: "Glittering lanes lined with hundreds of gold and jewellery traders.",
    tags: ["Shopping", "Culture"],
  },
  {
    id: "spice-souk",
    name: "Spice Souk",
    category: "Hidden Gems",
    coords: { x: 45, y: 20 },
    cost: 0,
    duration: 45,
    rating: 4.3,
    priceLevel: 1,
    distanceKm: 6.4,
    open: true,
    hiddenGem: true,
    description: "Fragrant stalls of saffron, frankincense and dried fruit near the creek.",
    tags: ["Culture", "Food", "History"],
  },
  {
    id: "jumeirah-beach",
    name: "Jumeirah Beach",
    category: "Outdoors",
    coords: { x: 30, y: 58 },
    cost: 0,
    duration: 120,
    rating: 4.6,
    priceLevel: 1,
    distanceKm: 8.3,
    open: true,
    hiddenGem: false,
    description: "Soft white sand with a clear view of the Burj Al Arab.",
    tags: ["Outdoors"],
  },
  {
    id: "kite-beach",
    name: "Kite Beach",
    category: "Outdoors",
    coords: { x: 26, y: 62 },
    cost: 0,
    duration: 90,
    rating: 4.7,
    priceLevel: 1,
    distanceKm: 9.1,
    open: true,
    hiddenGem: false,
    description: "Active beach hub for kite surfing, skate ramps and street food trucks.",
    tags: ["Outdoors", "Food"],
  },
  {
    id: "museum-future",
    name: "Museum of the Future",
    category: "Attractions",
    coords: { x: 58, y: 44 },
    cost: 149,
    duration: 90,
    rating: 4.6,
    priceLevel: 3,
    distanceKm: 2.0,
    open: true,
    hiddenGem: false,
    description: "An award-winning building exploring tomorrow's technology and design.",
    tags: ["Art", "Culture"],
  },
  {
    id: "dubai-frame",
    name: "Dubai Frame",
    category: "Attractions",
    coords: { x: 50, y: 26 },
    cost: 50,
    duration: 60,
    rating: 4.5,
    priceLevel: 2,
    distanceKm: 3.4,
    open: true,
    hiddenGem: false,
    description: "A 150m golden frame linking old and new Dubai with a glass skywalk.",
    tags: ["History", "Art"],
  },
  {
    id: "alserkal-avenue",
    name: "Alserkal Avenue",
    category: "Hidden Gems",
    coords: { x: 34, y: 46 },
    cost: 0,
    duration: 75,
    rating: 4.6,
    priceLevel: 2,
    distanceKm: 7.0,
    open: true,
    hiddenGem: true,
    description: "A warehouse arts district full of galleries, studios and specialty coffee.",
    tags: ["Art", "Culture"],
  },
  {
    id: "city-walk",
    name: "City Walk",
    category: "Shopping",
    coords: { x: 42, y: 50 },
    cost: 0,
    duration: 90,
    rating: 4.5,
    priceLevel: 3,
    distanceKm: 3.8,
    open: true,
    hiddenGem: false,
    description: "An open-air lifestyle district of boutiques, murals and restaurants.",
    tags: ["Shopping", "Food", "Art"],
  },
  {
    id: "la-mer",
    name: "La Mer",
    category: "Outdoors",
    coords: { x: 36, y: 56 },
    cost: 0,
    duration: 90,
    rating: 4.5,
    priceLevel: 2,
    distanceKm: 6.5,
    open: true,
    hiddenGem: false,
    description: "A colourful beachfront with street art, diners and watersports.",
    tags: ["Outdoors", "Food", "Art"],
  },
  {
    id: "dubai-marina",
    name: "Dubai Marina",
    category: "Attractions",
    coords: { x: 16, y: 70 },
    cost: 0,
    duration: 90,
    rating: 4.6,
    priceLevel: 3,
    distanceKm: 14.0,
    open: true,
    hiddenGem: false,
    description: "A glowing canal of skyscrapers, yachts and a lively promenade.",
    tags: ["Outdoors", "Food"],
  },
  {
    id: "jbr",
    name: "JBR - The Beach",
    category: "Food",
    coords: { x: 12, y: 74 },
    cost: 120,
    duration: 75,
    rating: 4.5,
    priceLevel: 3,
    distanceKm: 14.6,
    open: true,
    hiddenGem: false,
    description: "Beachside dining and cafes with your toes almost in the sand.",
    tags: ["Food", "Outdoors"],
  },
  {
    id: "global-village",
    name: "Global Village",
    category: "Events",
    coords: { x: 72, y: 30 },
    cost: 30,
    duration: 150,
    rating: 4.4,
    priceLevel: 2,
    distanceKm: 22.0,
    open: true,
    hiddenGem: false,
    description: "A seasonal world's-fair of pavilions, food and live performances.",
    tags: ["Food", "Music", "Shopping", "Culture"],
  },
  {
    id: "dubai-opera",
    name: "Dubai Opera",
    category: "Culture",
    coords: { x: 54, y: 50 },
    cost: 250,
    duration: 120,
    rating: 4.8,
    priceLevel: 4,
    distanceKm: 1.3,
    open: true,
    hiddenGem: false,
    description: "A dhow-shaped venue hosting opera, ballet and concerts downtown.",
    tags: ["Music", "Art", "Culture"],
  },
  {
    id: "madinat-jumeirah",
    name: "Madinat Jumeirah",
    category: "Culture",
    coords: { x: 22, y: 60 },
    cost: 0,
    duration: 90,
    rating: 4.7,
    priceLevel: 3,
    distanceKm: 10.2,
    open: true,
    hiddenGem: false,
    description: "A recreated Arabian village of canals, souks and Burj Al Arab views.",
    tags: ["Culture", "Shopping", "Food"],
  },
  {
    id: "ras-al-khor",
    name: "Ras Al Khor Wildlife Sanctuary",
    category: "Hidden Gems",
    coords: { x: 60, y: 20 },
    cost: 0,
    duration: 60,
    rating: 4.6,
    priceLevel: 1,
    distanceKm: 8.8,
    open: true,
    hiddenGem: true,
    description: "Free lagoon hides where flamingos gather minutes from downtown.",
    tags: ["Outdoors"],
  },
]

export const EVENTS: CityEvent[] = [
  {
    id: "ev-fountain",
    name: "Dubai Fountain Show",
    venue: "Burj Lake, Downtown",
    date: "2026-09-09",
    time: "20:00",
    price: 0,
    category: "Events",
    distanceKm: 1.4,
    today: true,
  },
  {
    id: "ev-jazz",
    name: "Sunset Jazz at the Marina",
    venue: "Dubai Marina Walk",
    date: "2026-09-09",
    time: "18:30",
    price: 75,
    category: "Events",
    distanceKm: 14.0,
    today: true,
  },
  {
    id: "ev-souk-nights",
    name: "Old Town Souk Nights",
    venue: "Al Seef Waterfront",
    date: "2026-09-09",
    time: "19:00",
    price: 0,
    category: "Culture",
    distanceKm: 4.1,
    today: true,
  },
  {
    id: "ev-artwalk",
    name: "Alserkal Late Gallery Walk",
    venue: "Alserkal Avenue",
    date: "2026-09-11",
    time: "17:00",
    price: 0,
    category: "Culture",
    distanceKm: 7.0,
    today: false,
  },
  {
    id: "ev-food-fest",
    name: "Creekside Food Festival",
    venue: "Dubai Creek Harbour",
    date: "2026-09-12",
    time: "16:00",
    price: 40,
    category: "Food",
    distanceKm: 6.9,
    today: false,
  },
  {
    id: "ev-opera",
    name: "Symphony Under the Stars",
    venue: "Dubai Opera Garden",
    date: "2026-09-13",
    time: "20:30",
    price: 250,
    category: "Events",
    distanceKm: 1.3,
    today: false,
  },
  {
    id: "ev-desert",
    name: "Desert Drum Circle",
    venue: "Al Marmoom Reserve",
    date: "2026-09-14",
    time: "18:00",
    price: 120,
    category: "Events",
    distanceKm: 30.0,
    today: false,
  },
  {
    id: "ev-market",
    name: "Ripe Farmers Market",
    venue: "Dubai Design District",
    date: "2026-09-13",
    time: "09:00",
    price: 0,
    category: "Food",
    distanceKm: 5.5,
    today: false,
  },
  {
    id: "ev-film",
    name: "Open-Air Film Night",
    venue: "The Beach, JBR",
    date: "2026-09-12",
    time: "21:00",
    price: 55,
    category: "Events",
    distanceKm: 14.6,
    today: false,
  },
  {
    id: "ev-heritage",
    name: "Heritage Craft Workshop",
    venue: "Al Fahidi District",
    date: "2026-09-15",
    time: "10:30",
    price: 90,
    category: "Culture",
    distanceKm: 4.6,
    today: false,
  },
]

export const ESSENTIALS = {
  currency: "UAE Dirham (AED)",
  emergency: "999 (Police) · 998 (Ambulance)",
  etiquette: [
    "Dress modestly in public areas and mosques — cover shoulders and knees.",
    "Never photograph people, especially women, without asking first.",
    "Public displays of affection and eating during daylight in Ramadan are frowned upon.",
  ],
}

export function placeById(id: string): Place | undefined {
  return PLACES.find((p) => p.id === id)
}

export function eventById(id: string): CityEvent | undefined {
  return EVENTS.find((e) => e.id === id)
}
